name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.modified, 'frontend/')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run frontend tests
        run: npm test

      - name: Azure login
        uses: Azure/docker-login@v1
        with:
         login-server: dockerimages1234.azurecr.io
         username: ${{ secrets.ACR_USERNAME }}
         password: ${{ secrets.ACR_PASSWORD }}
    
      - run: |
         docker build . -t dockerimages1234.azurecr.io/frontend:${{ github.sha }}
         docker push dockerimages1234.azurecr.io/frontend:${{ github.sha }}
