on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: docker/login-action@v3
          with:
            registry: dockerimages1234.azurecr.io
            username: ${{ secrets.ACR_USERNAM }}
            password: ${{ secrets.ACR_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.dockerimages1234 }}/sampleapp:${{ github.sha }}
            docker push ${{ secrets.dockerimages1234 }}/sampleapp:${{ github.sha }}
